### PR TITLE
fix: random number & dead-loop problems & perf: slightly optimize the value`s type of map

### PR DESCRIPTION
**Pull request by CoderI421**
#### fix: random number & dead-loop problems & perf: slightly optimize the value`s type of map
 * problem random: uses the provided seed value to initialize the function rand, for fixing the generation of the same int in the case of multiple executions.
 * problem dead-loop: in the case of the whole dict has few data(ex. 2 items), the function "RandomKeys" or "RandomDistinctKeys" is executed. When "RandomKeys" or "RandomDistinctKeys" has not completed execution and all data is cleared, it will be stuck in an endless loop. 
   I`m not sure whether my solution meets your expectation, it needs you to judge, if not I will close this PR. 
   My solution is as follow: when the number of cycles is an integer multiple of "limit * 2", recheck whether "limit >= dict.Len()"

#### perf: slightly optimize the value`s type of map to save memory space at datastruct/dict/concurrent.go

Have a nice day~

Limited ability, make it better~

### CODE REVIEW

**Comment by HDT3213** [comment]
It seems to me that what you are pointing out is a concurrency issue. During `RandomKeys` is executing, deleting keys in the dict may cause an endless loop. 

I think it is very hard to solve this problem without a mutex to the dict. Actually the function has not been called, so it is acceptable to just delete this function.

**Comment by CoderI421** [comment]
> It seems to me that what you are pointing out is a concurrency issue. During `RandomKeys` is executing, deleting keys in the dict may cause an endless loop.
> 
> I think it is very hard to solve this problem without a mutex to the dict. Actually the function has not been called, so it is acceptable to just delete this function.


Hi~
I agree with you that the essence of the problem is the problem of concurrent read/write lock.

For me, I just need to close this PR or need to re-PR? 
And if need to re-PR, what should I do when I re-PR, the coding without the part related to concurrent RWLock? or just need to delete the function "RandomKeys" or "RandomDistinctKeys"?

**Comment by HDT3213** [comment]
Just close this issue is fine

**Comment by CoderI421** [comment]
> 

ok~
Have a nice day~

**Comment by HDT3213** [comment]
Have a nice day~

**Pull request closed without merging**
